env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  no-console: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
